# Generated by Django 2.2.10 on 2021-02-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingType'),
        ),
    ]
