# Generated by Django 2.2.10 on 2022-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210401_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('update_hyperlink', models.URLField(max_length=2000, null=True)),
                ('update_address', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
