# Generated by Django 2.2.10 on 2022-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_updateinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinformation',
            name='update_address',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='updateinformation',
            name='update_hyperlink',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
