# Generated by Django 2.2.10 on 2022-12-23 07:42

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20221223_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinformation',
            name='update_logo',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('logo'), validators=[core.helpers.file_size_validator]),
        ),
    ]
