# Generated by Django 2.2.10 on 2021-02-14 17:07

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_qia_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='qia_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter'), verbose_name='QIA Certificate File'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='qia_certificate_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter/qr/'), verbose_name='QIA Certificate QR File'),
        ),
    ]
