# Generated by Django 2.2.10 on 2021-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210215_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icno',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='Identity Card Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qia_status',
            field=models.CharField(blank=True, choices=[('', 'Not Eligible'), ('need_review', 'Need Review'), ('need_payment', 'Need Payment'), ('approved', 'Approved')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'WP KUALA LUMPUR'), ('WILAYAH PERSEKUTUAN LABUAN', 'WP LABUAN'), ('WILAYAH PERSEKUTUAN PUTRAJAYA', 'WP PUTRAJAYA'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True),
        ),
    ]
