# Generated by Django 2.2.10 on 2021-02-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210218_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icno',
            field=models.CharField(max_length=14, null=True, verbose_name='Identity Card Number'),
        ),
    ]
