# Generated by Django 2.2.10 on 2021-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_qia_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qia_payment_status',
            field=models.CharField(choices=[('2', 'Pending Authorization (Applicable for B2B model)'), ('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending'), ('-2', '-')], default='-2', max_length=15),
        ),
    ]
