# Generated by Django 2.2.10 on 2021-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210408_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='greencard_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Green card number'),
        ),
    ]
