# Generated by Django 2.2.10 on 2021-04-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210416_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('contractor', 'Contractor'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], default='applicant', max_length=50, null=True),
        ),
    ]
