# Generated by Django 2.2.10 on 2021-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210421_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('contractor', 'Contractor'), ('none', 'None'), ('trainee', 'Trainee'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=50, null=True),
        ),
    ]
