# Generated by Django 2.2.10 on 2021-02-13 05:24

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_registration_grade', models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=3, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('GOVERNMENT', 'GOVERNMENT')], max_length=10, null=True, verbose_name='Project type @ Sector')),
                ('contract_type', models.CharField(blank=True, choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=50, null=True)),
                ('levy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ssm_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSM number')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Contract value (RM including GST)')),
                ('project_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('project_location', models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True)),
                ('project_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_of_award_date', models.DateField(blank=True, null=True, verbose_name='Letter of Award Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('dateline', models.DateField(blank=True, null=True, verbose_name='Dateline')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code')),
                ('registered_city', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_state', models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True)),
                ('correspondence_address', models.CharField(blank=True, max_length=255, null=True)),
                ('correspondence_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code')),
                ('correspondence_city', models.CharField(blank=True, max_length=255, null=True)),
                ('correspondence_state', models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('qlassic', 'QLASSIC'), ('mock_up', 'Mock up')], max_length=10, null=True)),
                ('project_title', models.CharField(max_length=2000, null=True)),
                ('project_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('GOVERNMENT', 'GOVERNMENT')], max_length=10, null=True, verbose_name='Project type @ Sector')),
                ('levy_number', models.CharField(max_length=10, null=True)),
                ('levy_receipt', models.FileField(blank=True, max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents'))),
                ('gfa', models.FloatField(null=True, verbose_name='Gross Floor Area (meter square)')),
                ('phase', models.CharField(max_length=10, null=True, verbose_name='Project phase')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Contract value (RM including GST)')),
                ('project_location', models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True)),
                ('project_reference_number', models.CharField(max_length=255, null=True)),
                ('project_manager', models.CharField(max_length=255, null=True)),
                ('developer', models.CharField(max_length=255, null=True)),
                ('developer_ssm_number', models.CharField(max_length=50, null=True)),
                ('architect_firm', models.CharField(max_length=255, null=True)),
                ('structural_civil_engineer_firm', models.CharField(max_length=255, null=True, verbose_name='Structural & Civil Engineer Firm')),
                ('mechanical_electrical_firm', models.CharField(max_length=255, null=True, verbose_name='M&E Engineer Firm')),
                ('contractor_name', models.CharField(max_length=255, null=True)),
                ('contractor_cidb_registration_no', models.CharField(max_length=255, null=True)),
                ('contractor_registration_grade', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=3, null=True)),
                ('site_representative', models.CharField(max_length=255, null=True)),
                ('hp_no', models.CharField(max_length=15, null=True, verbose_name='Contact number')),
                ('email', models.CharField(max_length=50, null=True)),
                ('iso9001', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have ISO 9001?')),
                ('shassic', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have SHASSIC?')),
                ('bim', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have BIM?')),
                ('gbi', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have GBI?')),
                ('mycrest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have MyCREST?')),
                ('construction_method', models.CharField(choices=[('ibs', 'IBS'), ('conventional', 'Conventional'), ('design_and_build', 'Design & Build'), ('pfi', 'PFI')], max_length=50, null=True)),
                ('ibs_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IBS percentage (%)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssm_number', models.CharField(max_length=255, null=True)),
                ('contractor_registration_number', models.CharField(max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
