# Generated by Django 2.2 on 2021-08-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210218_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='rating_type',
            field=models.CharField(choices=[('qlassic', 'QLASSIC')], max_length=10, null=True),
        ),
    ]
