# Generated by Django 2.2.10 on 2022-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210802_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_status',
            field=models.CharField(choices=[('reviewed', 'Reviewed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('is_being_assessed', 'is being assessed'), ('completed', 'Completed')], max_length=50, null=True),
        ),
    ]
