# Generated by Django 2.2.10 on 2023-02-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_submitfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='parent_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectInfo'),
        ),
    ]
