# Generated by Django 2.2.10 on 2021-02-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20210218_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='no_of_days',
            field=models.IntegerField(null=True, verbose_name='Number of Days'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='assessment_date',
            field=models.DateField(null=True, verbose_name='Assessment Date'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='no_of_blocks',
            field=models.IntegerField(null=True, verbose_name='Number of Block/Zone/Assessment'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='proposed_date',
            field=models.DateField(null=True, verbose_name='Proposed Date for Assessment'),
        ),
    ]
