# Generated by Django 2.2.10 on 2021-02-19 15:16

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20210219_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedassessor',
            name='role_in_assessment',
            field=models.CharField(choices=[('lead_assessor', 'Lead Assessor'), ('assessor', 'Assessor')], default='assessor', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='project_declaration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedassessor',
            name='acception',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Wait For Respond')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportingdocuments',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents'), validators=[core.helpers.file_size_validator]),
        ),
    ]
