# Generated by Django 2.2.10 on 2021-03-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_auto_20210220_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompletionform',
            name='icno',
            field=models.CharField(max_length=12, null=True, verbose_name="IC number (without '-')"),
        ),
    ]
