# Generated by Django 2.2.10 on 2021-03-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_auto_20210303_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectgroup',
            name='no_of_check',
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.IntegerField(choices=[(1, 'Complex (eg. Architectural Work)'), (2, 'Simple (eg. External Work)')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='sub_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SubComponent'),
        ),
        migrations.AddField(
            model_name='element',
            name='no_of_check',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1, null=True, verbose_name='Number of Check'),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='no_of_check',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1, null=True, verbose_name='Number of Check'),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='type',
            field=models.IntegerField(choices=[(3, 'With Element (eg. Internal Finishes)'), (4, 'Without Element (eg. Roof)')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='apron_perimeter_drain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='architectural_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='block',
            field=models.IntegerField(blank=True, null=True, verbose_name="Block's name"),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='car_park',
            field=models.FloatField(blank=True, null=True, verbose_name='Car park/ Car porch'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='ceiling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='count_circulation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of circulation samples'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='count_principle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of principles samples'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='count_sampling_done',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of sampling done'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='count_services',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of services samples'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='door',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='external_wall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='floor_finishes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='internal_fixtures',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='internal_wall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='material_functional_test',
            field=models.FloatField(blank=True, null=True, verbose_name='Material & Functional Test'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='me_fittings',
            field=models.FloatField(blank=True, null=True, verbose_name='Basic M&E Fittings'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='mock_up_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC score with mock up'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='number_of_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='qaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='qlassic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC score'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='roof',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time taken to complete data for one sample'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total (1.1-5)'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unit number'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='window',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defectgroup',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Element'),
        ),
    ]
