# Generated by Django 2.2.10 on 2021-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20210305_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='weightage',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Weightage (%)'),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='weightage',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Weightage (%)'),
        ),
    ]
