# Generated by Django 2.2.10 on 2021-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_auto_20210308_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sub_component_weightage',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='weightage',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Weightage (%)'),
        ),
    ]
