# Generated by Django 2.2.10 on 2021-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_auto_20210308_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sub_component_weightage',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
