# Generated by Django 2.2.10 on 2021-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_auto_20210315_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
