# Generated by Django 2.2.10 on 2021-03-16 07:10

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_auto_20210316_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('test_type', models.CharField(blank=True, max_length=255, null=True)),
                ('selection_value', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('element_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dg_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_compliance', models.IntegerField(default=0, null=True)),
                ('total_check', models.IntegerField(default=0, null=True)),
                ('photo_1', models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos'))),
                ('photo_2', models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos'))),
                ('photo_3', models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos'))),
                ('photo_4', models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
                ('sample_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SampleResult')),
            ],
        ),
    ]
