# Generated by Django 2.2.10 on 2021-03-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_elementresult_sampleresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='qaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
    ]
