# Generated by Django 2.2.10 on 2021-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_sampleresult_qaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementresult',
            name='remark',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='elementresult',
            name='sample_run',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
