# Generated by Django 2.2.10 on 2021-03-17 03:03

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_auto_20210316_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='photo',
            field=models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos/1')),
        ),
    ]
