# Generated by Django 2.2.10 on 2021-03-17 04:09

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_sampleresult_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementresult',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='elementresult',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='elementresult',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='elementresult',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='elementresult',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='elementresult',
            name='sample_run',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='photo',
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='photo_1',
            field=models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos')),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='photo_2',
            field=models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos')),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='photo_3',
            field=models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos')),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='photo_4',
            field=models.FileField(max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos')),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='remark',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='sample_run',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
