# Generated by Django 2.2.10 on 2021-03-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_auto_20210317_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleresult',
            name='assessors',
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='assessor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='assessor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='partners',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
