# Generated by Django 2.2.10 on 2021-03-17 07:58

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_auto_20210317_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementresult',
            name='test_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleresult',
            name='photo_1',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos1')),
        ),
        migrations.AlterField(
            model_name='sampleresult',
            name='photo_2',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos2')),
        ),
        migrations.AlterField(
            model_name='sampleresult',
            name='photo_3',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos3')),
        ),
        migrations.AlterField(
            model_name='sampleresult',
            name='photo_4',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/photos4')),
        ),
    ]
