# Generated by Django 2.2.10 on 2021-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_sampleresult_element_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='element_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
