# Generated by Django 2.2.10 on 2021-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_sampleresult_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementresult',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
