# Generated by Django 2.2.10 on 2021-03-17 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_auto_20210317_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementresult',
            name='sync_id',
        ),
        migrations.RemoveField(
            model_name='sampleresult',
            name='sync_id',
        ),
        migrations.AddField(
            model_name='elementresult',
            name='sync_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='sync_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SyncResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
        migrations.AddField(
            model_name='elementresult',
            name='sync',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SyncResult'),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='sync',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SyncResult'),
        ),
    ]
