# Generated by Django 2.2.10 on 2021-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_auto_20210317_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncresult',
            name='assessor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
