# Generated by Django 2.2.10 on 2021-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_syncresult_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncresult',
            name='coordinate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
