# Generated by Django 2.2.10 on 2021-03-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_syncresult_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomponent',
            name='weightage',
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_a',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='Weightage A'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_b',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='Weightage B'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_c',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='Weightage C'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_d',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='Weightage D'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weightage',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='Weightage'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weightage_a',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='Weightage A'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weightage_b',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='Weightage B'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weightage_c',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='Weightage C'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weightage_d',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='Weightage D'),
        ),
    ]
