# Generated by Django 2.2.10 on 2021-03-19 08:57

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_auto_20210318_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteattendance',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='workcompletionform',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='workcompletionform',
            name='project_location',
        ),
        migrations.AddField(
            model_name='workcompletionform',
            name='coordinate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workcompletionform',
            name='signature',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.helpers.PathAndRename('qaa/signature')),
        ),
        migrations.AddField(
            model_name='workcompletionform',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessment_end_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Assessment end date'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Assessment start date'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessor_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='hp_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='icno',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="IC number (without '-')"),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='number_of_form_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='number_of_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='qaa_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QLASSIC Assessment Application number'),
        ),
    ]
