# Generated by Django 2.2.10 on 2021-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_siteattendance_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Assessment end date'),
        ),
    ]
