# Generated by Django 2.2.10 on 2021-03-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_auto_20210319_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='defectgroup',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='subcomponent',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='syncresult',
            name='result',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
