# Generated by Django 2.2.10 on 2021-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_auto_20210328_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncresult',
            name='label',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
