# Generated by Django 2.2.10 on 2021-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_syncresult_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdata',
            name='ctotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='ptotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='stotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
