# Generated by Django 2.2.10 on 2021-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_auto_20210329_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedassessor',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
