# Generated by Django 2.2.10 on 2021-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_assignedassessor_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='payment_status',
            field=models.CharField(choices=[('2', 'Pending Authorization (Applicable for B2B model)'), ('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending'), ('-2', '-')], default='-2', max_length=15, null=True),
        ),
    ]
