# Generated by Django 2.2.10 on 2021-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_qlassicassessmentapplication_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlassicreporting',
            name='ad',
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_certificate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_score_letter_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved')], default='pending', max_length=20, null=True),
        ),
    ]
