# Generated by Django 2.2.10 on 2021-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_auto_20210331_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='casc_qlassic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC score from CASC'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_certificate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('casc_approved', 'CASC Approved'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved'), ('submit', 'Delivered to Applicant')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('casc_approved', 'CASC Approved'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved'), ('submit', 'Delivered to Applicant')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='doc_qlassic_score_letter_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Report Generated'), ('casc_approved', 'CASC Approved'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('approved', 'Approved'), ('submit', 'Delivered to Applicant')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='qlassic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC score'),
        ),
    ]
