# Generated by Django 2.2.10 on 2021-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_qlassicassessmentapplication_ccd_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='casc_qlassic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC score from CASC Approver (Leave blank for actual score)'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='ccd_point',
            field=models.FloatField(null=True, verbose_name='CCD Point'),
        ),
    ]
