# Generated by Django 2.2.10 on 2021-03-31 15:07

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_auto_20210331_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='qlassic_certificate_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('assessment/qr/'), verbose_name='QLASSIC Cert QR File'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='qlassic_report_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('assessment/qr/'), verbose_name='QLASSIC Report QR File'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='qlassic_score_letter_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('assessment/qr/'), verbose_name='QLASSIC Score QR File'),
        ),
    ]
