# Generated by Django 2.2.10 on 2021-03-31 16:30

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_auto_20210401_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicreporting',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('assessment/report/'), verbose_name='Report File'),
        ),
    ]
