# Generated by Django 2.2.10 on 2021-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0046_qlassicreporting_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicreporting',
            name='code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
