# Generated by Django 2.2.10 on 2021-04-08 06:55

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_qlassicreporting_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocuments',
            name='reviewed_file',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents/reviewed'), validators=[core.helpers.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='verified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
