# Generated by Django 2.2.10 on 2021-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_auto_20210507_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='scope',
            field=models.TextField(null=True),
        ),
    ]
