# Generated by Django 2.2 on 2021-10-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_auto_20210507_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='weightage_a',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Weightage A'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_b',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Weightage B'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_c',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Weightage C'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weightage_d',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Weightage D'),
        ),
    ]
