# Generated by Django 2.2.10 on 2022-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0054_auto_20211015_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleresult',
            name='remark',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedassessor',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
