# Generated by Django 2.2.10 on 2023-02-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0055_auto_20221222_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='parent_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
    ]
