# Generated by Django 2.2.10 on 2023-02-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0056_qlassicassessmentapplication_parent_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='parent_obj',
        ),
    ]
