# Generated by Django 2.2.10 on 2021-02-13 05:24

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(max_length=50, null=True)),
                ('claim_category', models.CharField(choices=[('mileage', 'Mileage'), ('fi', 'FI'), ('public_transport', 'Public Transport'), ('accommodation', 'Accommodation'), ('others', 'Others')], max_length=50, null=True)),
                ('claim_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('approved', 'Approved')], default='pending', max_length=50, null=True)),
                ('other_type', models.CharField(choices=[('mileage', 'Mileage'), ('fi', 'FI'), ('public_transport', 'Public Transport'), ('accommodation', 'Accommodation'), ('others', 'Others')], max_length=50, null=True)),
                ('transport_type', models.CharField(choices=[('airplane', 'Airplane'), ('train', 'Train'), ('car', 'Car'), ('bus', 'Bus')], max_length=50, null=True)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('lojing', 'Lojing')], max_length=50, null=True)),
                ('location_from', models.CharField(blank=True, max_length=255, null=True)),
                ('location_to', models.CharField(blank=True, max_length=255, null=True)),
                ('state_from', models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True)),
                ('state_to', models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('transport_model', models.CharField(max_length=50, null=True, verbose_name='Transport Model')),
                ('transport_cc', models.FloatField(null=True, verbose_name='CC')),
                ('transport_registration_number', models.CharField(max_length=50, null=True, verbose_name='Transport Registration Number')),
                ('notes', models.CharField(max_length=255, null=True)),
                ('mileage', models.FloatField(null=True)),
                ('receipt_number', models.CharField(max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('total_receipt_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Amount')),
                ('date_of_transaction', models.DateField(null=True, verbose_name='Date of Transaction')),
                ('attachments', models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('billings'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditDebitCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=50, null=True, verbose_name='Credit/ Debit card number')),
                ('name_on_card', models.CharField(max_length=255, null=True)),
                ('expired_date', models.DateField(null=True, verbose_name='Expired date (month/year)')),
                ('cvc', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_description', models.CharField(max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('saving_account', 'Saving Account')], max_length=50, null=True)),
                ('account_bank', models.CharField(choices=[('cimbclicks', 'CIMB Clicks'), ('maybank2u', 'Maybank2u'), ('affinbank', 'Affin Bank'), ('bsn', 'Bank Simpanan Nasional')], max_length=50, null=True)),
                ('account_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount (RM)')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('FPX', 'Online Banking'), ('CCX', 'Credit/ Debit card')], max_length=50, null=True)),
                ('payment_method_description', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('1', 'Successfull'), ('0', 'Fail'), ('-1', 'Pending')], default='-1', max_length=15)),
                ('status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('qaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_description', models.CharField(max_length=255, null=True)),
                ('receipt_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice')], max_length=50, null=True)),
                ('receipt_description', models.CharField(max_length=255, null=True)),
                ('cdc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.CreditDebitCard')),
                ('ob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.OnlineBanking')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment')),
            ],
        ),
    ]
