# Generated by Django 2.2.10 on 2021-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_auto_20210218_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending')], default='-1', max_length=15),
        ),
    ]
