# Generated by Django 2.2.10 on 2021-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_auto_20210224_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('2', 'Proforma Cancelled'), ('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending')], default='-1', max_length=15),
        ),
    ]
