# Generated by Django 2.2.10 on 2021-03-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_auto_20210324_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proforma_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending')], default='-1', max_length=15),
        ),
    ]
