# Generated by Django 2.2.10 on 2021-02-13 05:24

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=100, null=True)),
                ('hp_no', models.CharField(max_length=15, null=True, verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(max_length=50, null=True)),
                ('description_1', models.TextField(blank=True, max_length=3000, null=True)),
                ('description_2', models.TextField(blank=True, max_length=3000, null=True)),
                ('warning', models.TextField(blank=True, max_length=3000, null=True)),
                ('warning_delivered', models.BooleanField(default=False, null=True)),
                ('warning_delivered_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True, verbose_name='Year join the training')),
                ('course', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('need_payment', 'Need Payment')], default='pending', max_length=40, null=True, verbose_name='Status')),
                ('participant_name', models.CharField(max_length=200, null=True, verbose_name="Participant's name")),
                ('participant_icno', models.CharField(max_length=14, null=True, verbose_name="Participant's IC number")),
                ('participant_email', models.CharField(max_length=100, null=True, verbose_name="Participant's email")),
                ('participant_hpno', models.CharField(max_length=15, null=True, verbose_name="Participant's phone number")),
                ('participant_designation', models.CharField(max_length=200, null=True, verbose_name="Participant's designation")),
                ('participant_organization', models.CharField(max_length=200, null=True, verbose_name="Participant's organization")),
                ('participant_organization_type', models.CharField(choices=[('Contractor', 'Contractor'), ('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Individual ', 'Individual')], default=True, max_length=50, null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('payment_mode', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default=True, max_length=5, null=True)),
                ('attendance_full', models.BooleanField(blank=True, choices=[(True, 'FULL'), (False, 'NOT FULL')], null=True)),
                ('pass_status', models.BooleanField(blank=True, choices=[(True, 'PASS'), (False, 'FAIL')], null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount (RM)')),
                ('paid', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('certificates'), verbose_name='Certificate')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(blank=True, max_length=255, null=True)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('interview_invitation', 'Interview Invitation'), ('approved', 'Approved'), ('reject', 'Rejected')], default='', max_length=255, null=True)),
                ('application_type', models.CharField(choices=[('qca', 'QLASSIC CIDB Assessor'), ('trainer', 'Trainer')], default='', max_length=255, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time_from', models.TimeField(blank=True, null=True)),
                ('interview_time_to', models.TimeField(blank=True, null=True)),
                ('interview_location', models.TextField(blank=True, max_length=2000, null=True)),
                ('interview_letter_file', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter'), verbose_name='Interview Letter')),
                ('interview_sent', models.BooleanField(default=False, null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('approved_by', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('training_name', models.CharField(max_length=255, null=True, verbose_name='Training Name')),
                ('from_date', models.DateField(null=True, verbose_name='Start Date')),
                ('to_date', models.DateField(null=True, verbose_name='End Date')),
                ('from_time', models.TimeField(null=True, verbose_name='Start Time')),
                ('to_time', models.TimeField(null=True, verbose_name='End Time')),
                ('size', models.IntegerField(null=True, verbose_name='Available Seat')),
                ('passing_mark', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Passing Mark')),
                ('ccd_point', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='CCD Point')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Fees (RM)')),
                ('reviewed_by', models.CharField(max_length=50, null=True)),
                ('reviewed_date', models.DateTimeField(null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=40, null=True, verbose_name='Status')),
                ('attendance_review_status', models.CharField(choices=[('pending', 'Pending'), ('need_approval', 'Submit For Approval'), ('approved', 'Approved')], default='pending', max_length=40, null=True, verbose_name='Attendance Review Status')),
                ('cert_type', models.CharField(choices=[('attendance', 'Attendance'), ('pass', 'Pass')], max_length=30, null=True, verbose_name='Certificate Type')),
                ('attendance_sheet_file', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('attendance_sheet'), verbose_name='Attendance Sheet')),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=10, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True)),
                ('publish', models.BooleanField(default=False, verbose_name='Published?')),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('required_for_assessor', models.BooleanField(default=False, null=True, verbose_name='Required For Becoming Assessor?')),
                ('template_file', models.FileField(null=True, upload_to=core.helpers.PathAndRename('templates'))),
                ('cert_type', models.CharField(choices=[('attendance', 'Attendance'), ('pass', 'Pass')], max_length=30, null=True, verbose_name='Certificate Type')),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('module1', 'Module 1'), ('module2', 'Module 2'), ('exam_practical_test', 'Exam Practical Test')], max_length=255, null=True)),
                ('participant_name', models.CharField(max_length=255, null=True, verbose_name="Participant's name")),
                ('attendance_full', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('marks', models.FloatField(null=True)),
                ('certificate_description', models.CharField(choices=[('attendance', 'Attendance'), ('marks', 'Marks')], max_length=10, null=True)),
                ('fees', models.CharField(max_length=4, null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('reviewed_date', models.DateField(null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=10, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.RegistrationTraining')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
        ),
    ]
