# Generated by Django 2.2.10 on 2021-02-14 04:54

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20210213_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='accreditation_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter'), verbose_name='Accreditation Certificate'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='accreditation_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter'), verbose_name='Accreditation Letter'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='reject_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter'), verbose_name='Rejection Letter'),
        ),
    ]
