# Generated by Django 2.2.10 on 2021-02-14 08:17

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20210214_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='certificate_qr_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter/qr/'), verbose_name='QR File'),
        ),
    ]
