# Generated by Django 2.2.10 on 2021-02-14 08:19

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_roleapplication_certificate_qr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='certificate_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('interview_letter/qr/'), verbose_name='QR File'),
        ),
    ]
