# Generated by Django 2.2.10 on 2021-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20210218_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtraining',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (RM)'),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
