# Generated by Django 2.2.10 on 2021-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20210303_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='payment_status',
            field=models.CharField(choices=[('2', 'Pending Authorization (Applicable for B2B model)'), ('1', 'Successful'), ('0', 'Fail'), ('-1', 'Pending'), ('-2', '-')], default='-1', max_length=15),
        ),
    ]
