# Generated by Django 2.2.10 on 2021-03-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_auto_20210330_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtraining',
            name='payment_mode',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=5, null=True),
        ),
    ]
