# Generated by Django 2.2.10 on 2022-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_auto_20210401_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
